/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment;

import javax.swing.JOptionPane;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.List;

import assignment.UserType;
import assignment.Adminstrator.Administrator;
import assignment.Adminstrator.adminstratorPage;
import assignment.PurchaseManager.PurchaseManager;
import assignment.PurchaseManager.purchaseManagerPage;
import assignment.SalesManager.SalesManager;
import assignment.SalesManager.salesManagerPage;
import assignment.FinanceManager.FinanceManager;
import assignment.FinanceManager.financeManagerPage;
import assignment.InventoryManager.InventoryManager;
import assignment.InventoryManager.inventoryManagerPage;
import assignment.Session;

/**
 *
 * @author Admin
 */
public class Login extends javax.swing.JFrame {

  private Session session;

  /**
   * Creates new form Login
   */
  public Login() {
    initComponents();
    this.session = Session.getInstance();
    getRootPane().setDefaultButton(loginButton);
  }

  public Login(Session session) {
    initComponents();
    this.session = session;
    getRootPane().setDefaultButton(loginButton);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    jLabel5 = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jPasswordField1 = new javax.swing.JPasswordField();
    jTextField2 = new javax.swing.JTextField();
    loginButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Login");
    setPreferredSize(new java.awt.Dimension(800, 500));

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));
    jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
    jPanel1.setLayout(null);

    jPanel2.setBackground(new java.awt.Color(0, 0, 0));
    jPanel2.setPreferredSize(new java.awt.Dimension(400, 500));

    jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(255, 255, 255));
    jLabel5.setText("Java Assignment");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel5)
                .addContainerGap(124, Short.MAX_VALUE)));
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(326, Short.MAX_VALUE)));

    jPanel1.add(jPanel2);
    jPanel2.setBounds(0, 0, 390, 520);

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
    jLabel1.setText("Login");
    jPanel1.add(jLabel1);
    jLabel1.setBounds(530, 60, 100, 50);

    jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel2.setText("Username or Email");
    jPanel1.add(jLabel2);
    jLabel2.setBounds(440, 154, 110, 20);

    jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel3.setText("Password");
    jPanel1.add(jLabel3);
    jLabel3.setBounds(440, 260, 60, 14);
    jPanel1.add(jPasswordField1);
    jPasswordField1.setBounds(440, 280, 310, 50);

    jTextField2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
    jTextField2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextField2ActionPerformed(evt);
      }
    });
    jPanel1.add(jTextField2);
    jTextField2.setBounds(440, 180, 310, 50);

    loginButton.setBackground(new java.awt.Color(0, 0, 0));
    loginButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    loginButton.setForeground(new java.awt.Color(255, 255, 255));
    loginButton.setText("Login");
    loginButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        loginButtonActionPerformed(evt);
      }
    });
    jPanel1.add(loginButton);
    loginButton.setBounds(440, 360, 310, 40);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 515,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField2ActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_jTextField2ActionPerformed

  private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
    String email = jTextField2.getText();
    String password = new String(jPasswordField1.getPassword()).trim();

    if (email.isEmpty() || password.isEmpty()) {
      JOptionPane.showMessageDialog(this, "Please enter both email and password");
      return;
    }

    UserType user = authenticate(email, password);
    if (user != null) {

      // Set session data
      session.setSessionData(user.getUser().getUserId(), user.getUser().getUsername(), user,
          user.getAccessLevel());

      // Handle user type pages
      if (user instanceof Administrator) {

        adminstratorPage adminFrame = new adminstratorPage();
        adminFrame.setVisible(true);
        adminFrame.pack();
        adminFrame.setLocationRelativeTo(null);
        this.dispose();

      } else if (user instanceof SalesManager) {

        salesManagerPage salesFrame = new salesManagerPage();
        salesFrame.setVisible(true);
        salesFrame.pack();
        salesFrame.setLocationRelativeTo(null);
        this.dispose();

      } else if (user instanceof PurchaseManager) {

        purchaseManagerPage purchaseFrame = new purchaseManagerPage();
        purchaseFrame.setVisible(true);
        purchaseFrame.pack();
        purchaseFrame.setLocationRelativeTo(null);
        this.dispose();

      } else if (user instanceof FinanceManager) {

        financeManagerPage financeFrame = new financeManagerPage();
        financeFrame.setVisible(true);
        financeFrame.pack();
        financeFrame.setLocationRelativeTo(null);
        this.dispose();

      } else if (user instanceof InventoryManager) {

        inventoryManagerPage inventoryFrame = new inventoryManagerPage();
        inventoryFrame.setVisible(true);
        inventoryFrame.pack();
        inventoryFrame.setLocationRelativeTo(null);
        this.dispose();

      }
    } else {
      JOptionPane.showMessageDialog(this, "Invalid email or password");
      jPasswordField1.setText("");
    }
  }// GEN-LAST:event_jButton2ActionPerformed

  private UserType authenticate(String email, String password) {
    FileHandler fileHandler = new FileHandler("src/assignment/database/users.txt");
    List<String[]> users = fileHandler.readData();

    for (String[] user : users) {
      if ((user[1].equals(email) || user[2].equals(email)) && user[4].equals(password)) {
        int accessLevel = Integer.parseInt(user[3]);
        UserType userType = createUserByAccessLevel(accessLevel);
        if (userType != null) {
          userType.setUser(new User(user[0], user[1], user[2], user[4], userType));
        }
        return userType;
      }
    }
    return null;
  }

  private UserType createUserByAccessLevel(int accessLevel) {
    switch (accessLevel) {
      case 1:
        return new Administrator();
      case 2:
        return new PurchaseManager();
      case 3:
        return new SalesManager();
      case 4:
        return new FinanceManager();
      case 5:
        return new InventoryManager();
      default:
        return null;
    }
  }

  private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
    changePassword changePasswordFrame = new changePassword();
    changePasswordFrame.setVisible(true);
    changePasswordFrame.pack();
    changePasswordFrame.setLocationRelativeTo(null);
    this.dispose();

  }// GEN-LAST:event_jButton3ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default
     * look and feel.
     * For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        Session session = Session.getInstance();
        Login LoginFrame = new Login(session);
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPasswordField jPasswordField1;
  private javax.swing.JTextField jTextField2;
  private javax.swing.JButton loginButton;
  // End of variables declaration//GEN-END:variables
}
